### ISSUE TITLE
Error with RR: undefined method `to_sym' for ActiveRecord::Base:Class

### ISSUE THREAD

**Issue by jomontanari** [rspec/rspec-dev#59]
I've been using RR for mocks and stubs with RSpec 2.99. When I upgraded to 3.0.0.beta2 I got the following error in the tests:
Failure/Error: stub(ActiveRecord::Base).transaction
     NoMethodError:
       undefined method `to_sym' for ActiveRecord::Base:Class

The code we were using to stub with RR looked like this:
stub(object).method 

I've fixed the code to use RSpec mocks now but raising the issue in case others want to use RR. I was using the latest version.
